const pdfBirth = async () => {
  // 77040077761
  const layoutReal = {
    info: {
      title: 'filename',
      author: 'Core Solutions Co.,Ltd.',
      subject: 'subject of document',
      keywords: 'keywords for document',
    },
    content: [
      {
        fontSize: 14,
        style: 'data',
        alignment: 'left',
        text: ['Thor.Ror. 1/Gor'],
      },
      {
        style: 'data',
        alignment: 'right',
        text: ['Ref:1099.101.85244'],
      },
      {
        style: 'header',
        text: ['Certified Form of Birth Registration (Birth Certificate)\n\n'],
      },  
      {
        fontSize: 13,
        table: {
          widths: ['64.7%', '35.35%'],
          body: [
            [
              { text: '' },
              {
                text: '',
                style: 'fieldName',
                alignment: 'center',
                border: [true, true, false, false],
              },
            ],
            [
              {
                border: [false, false, true, false],
                columns: [
                  {
                    width: 90,
                    style: 'fieldName',
                    text: 'Registration Office:',
                    margin: [0, 0, 0, 0],
                  },
                  {
                    width: '*',
                    fontSize: 13,
                    style: 'data',
                    text: 'Bang Khen District',
                    margin: [-4, 0, 0, 0],
                  },
                ],
              },
              {
                style: 'data',
                text: 'Identification No. 1-1005-01661-29-5',
                alignment: 'center',
                border: [true, false, false, false],
              },
            ],
          ],
        },
        layout: {
          defaultBorder: false,
        },
      },
      {
        fontSize: 13,
        table: {
          widths: [
            '9%',
            '17%',
            '10%',
            '10%',
            '10%',
            '7%',
            '-1%',
            '11%',
            '10%',
            '16%',
          ],
          body: [
            [
              {
                text: '1.\nThe\nNewborn',
                bold: true,
                alignment: 'center',
                border: [false, true, false, true],
                fontSize: 16,
                rowSpan: 8,
                margin: [-5, 0, 0, 0],
              },
              {
                text: '1.1 Name - Surname',
                style: 'fieldName',
                alignment: 'left',
                border: [true, true, true, false],
                colSpan: 4,
              },
              { text: '' },
              { text: '' },
              { text: '' },
              {
                text: '1.2 Sex',
                style: 'fieldName',
                alignment: 'left',
                border: [false, true, true, false],
                colSpan: 2,
              },
              { text: '' },
              {
                text: '1.3 Nationality',
                style: 'fieldName',
                alignment: 'left',
                border: [false, true, false, false],
                colSpan: 3,
              },
              { text: '' },
              { text: '' },
            ],
            [
              { text: '' },
              {
                style: 'data',
                text: 'MASTER SUWAROON UDOMSUPRASERT',
                alignment: 'left',
                border: [true, false, false, false],
                colSpan: 4,
                margin: [20, 0, 0, 3],
              },
              { text: '' },
              { text: '' },
              { text: '' },
              {
                style: 'data',
                text: 'Male',
                alignment: 'left',
                border: [true, false, true, false],
                colSpan: 2,
                margin: [10, 0, 0, 0],
              },
              { text: '' },
              {
                style: 'data',
                text: 'Thai',
                alignment: 'left',
                border: [false, false, false, false],
                colSpan: 3,
                margin: [10, 0, 0, 0],
              },
              { text: '' },
              { text: '' },
            ],
            [
              { text: '' },
              {
                colSpan: 2,
                border: [true, true, false, true],
                columns: [
                  {
                    width: 70,
                    style: 'fieldName',
                    text: [
                      { text: '1.4 Date of Birth\n'},
                      { text: '30 June 2005'}
                    ],
                    margin: [0, 1, 0, 2],
                  },
                  {
                    width: 15,
                    fontSize: 13,
                    style: '',
                    text: '',
                    margin: [0, 1, 0, 2],
                  },
                  {
                    width: 26,
                    style: 'fieldName',
                    text: '',
                    margin: [0, 1, 0, 2],
                  },
                  {
                    width: '*',
                    fontSize: 13,
                    style: 'data',
                    text: '',
                    margin: [0, 1, 0, 2],
                  },
                  {
                    width: 22,
                    style: 'fieldName',
                    text: '',
                    margin: [3, 1, 0, 2],
                  },
                  {
                    width: '*',
                    fontSize: 13,
                    style: 'data',
                    text: '',
                    margin: [0, 1, 0, 2],
                  },
                ],
              },
              { text: '' },
              {
                border: [true, true, false, true],
                columns: [
                  {
                    width: '*',
                    style: 'fieldName',
                    text: 'Time',
                    margin: [0, 1, 0, 2],
                  },
                  {
                    width: '*',
                    fontSize: 13,
                    style: 'data',
                    text: '',
                    margin: [-2, 0, 2, 2],
                  },
                  {
                    width: '*',
                    style: 'fieldName',
                    text: '',
                    margin: [0, 1, 0, 2],
                  },
                ],
              },
              {
                colSpan: 2,
                border: [true, true, false, true],
                columns: [
                  {
                    width: '*',
                    style: 'fieldName',
                    text: ' Corresponding to the Day',
                    margin: [0, 1, 0, 2],
                  },
                  {
                    width: '*',
                    fontSize: 13,
                    style: 'data',
                    text: '',
                    margin: [2, 0, 0, 2],
                  },
                ],
              },
              { text: '' },
              {
                colSpan: 2,
                border: [true, true, false, true],
                columns: [
                  {
                    width: '*',
                    fontSize: 13,
                    style: 'data',
                    alignment: 'left',
                    text: 'Waning',
                    margin: [-2, 0, 0, 2],
                  },
                  {
                    width: '*',
                    style: 'fieldName',
                    text: '',
                    alignment: 'right',
                    margin: [0, 1, 9, 2],
                  },
                ],
              },
              { text: '' },
              {
                border: [true, true, false, true],
                columns: [
                  {
                    width: '*',
                    style: 'fieldName',
                    alignment: 'left',
                    text: 'Lunar Month',
                    margin: [0, 1, 0, 2],
                  },
                  {
                    width: '*',
                    fontSize: 13,
                    style: 'data',
                    text: '',
                    alignment: 'center',
                    margin: [0, 0, 0, 2],
                  },
                ],
              },
              {
                border: [true, true, false, true],
                columns: [
                  {
                    width: 10,
                    style: 'fieldName',
                    alignment: 'left',
                    text: '',
                    margin: [0, 1, 0, 2],
                  },
                  {
                    width: 40,
                    fontSize: 13,
                    style: 'data',
                    text: 'Year of the',
                    alignment: 'left',
                    margin: [0, 0, 0, 2],
                  },
                ],
              },
            ],
            [
              { text: '' },
              {
                border: [true, false, false, false],
                columns: [
                  {
                    width: 70,
                    style: 'fieldName',
                    text: '1.5 Place of Birth',
                    margin: [0, 0, 0, 0],
                  },
                  {
                    width: 400,
                    fontSize: 13,
                    style: 'data',
                    text: '',
                    margin: [0, 0, 0, 0],
                  },
                ],
              },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '', border: [false, false, false, false] },
            ],
            [
              { text: '' },
              {
                style: 'data',
                text: '362/114 Village No.8 Anusaowari Sub-district, Bang Khen District, Bangkok Metropolis\n',
                alignment: 'left',
                border: [true, false, false, false],
                colSpan: 9,
                margin: [70, 0, 0, 5],
              },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
            ],
            [
              { text: '' },
              {
                border: [true, true, false, true],
                colSpan: 2,
                columns: [
                  {
                    width: 100,
                    style: 'fieldName',
                    text: '1.6 Being the Child No',
                    margin: [0, 1, 0, 2],
                  },
                  {
                    width: 400,
                    fontSize: 13,
                    style: 'data',
                    text: '1',
                    margin: [0, 1, 0, 2],
                  },
                ],
              },
              { text: '' },
              {
                colSpan: 3,
                border: [true, true, false, true],
                columns: [
                  {
                    width: 100,
                    style: 'fieldName',
                    text: '1.7 Birth Delivery Person',
                    margin: [0, 1, 0, 2],
                  },
                  {
                    width: 400,
                    fontSize: 13,
                    style: 'data',
                    text: 'Physician',
                    margin: [0, 1, 0, 2],
                  },
                ],
              },
              { text: '' },
              { text: '' },
              {
                text: '1.8 Weight at Birth ',
                style: 'fieldName',
                alignment: 'left',
                border: [true, true, false, true],
                colSpan: 2,
                margin: [0, 1, -50, 2],
              },
              { text: '' },
              {
                text: '2,880',
                style: 'data',
                alignment: 'right',
                border: [false, true, false, true],
                margin: [0, 1, 0, 2],
              },
              {
                text: 'grams',
                style: 'fieldName',
                alignment: 'right',
                border: [false, true, false, true],
                margin: [0, 1, 0, 2],
              },
            ],
            [
              { text: '' },
              {
                text: '1.9 Name Added to the House Registration No',
                style: 'fieldName',
                alignment: 'left',
                border: [true, false, false, false],
                colSpan: 6,
                margin: [0, 3, 0, 0],
              },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              {
                text: '1.10 House Code No. where name is added:',
                style: 'fieldName',
                alignment: 'center',
                border: [true, false, false, false],
                colSpan: 3,
                fontSize: 13,
              },
              { text: '' },
              { text: '' },
            ],
            [
              { text: '' },
              {
                style: 'data',
                text: ' Central House Registration 14\nAnusaowari Sub-district, Bang Khen District, Bangkok Metropolis\n',
                alignment: 'left',
                border: [true, false, false, true],
                colSpan: 6,
                margin: [30, -3, 0, 3],
              },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              {
                style: 'data',
                text: '1005-014515-1',
                alignment: 'center',
                border: [true, false, false, true],
                colSpan: 3,
              },
              { text: '' },
              { text: '' },
            ],
            [
              {
                text: '2.\nMother\n',
                bold: true,
                style: 'fieldName',
                alignment: 'center',
                border: [false, false, false, true],
                fontSize: 16,
                rowSpan: 5,
                margin: [-5, 0, 0, 0],
              },
              {
                text: '2.1 Name - Maiden Name',
                style: 'fieldName',
                alignment: 'left',
                border: [true, true, true, false],
                colSpan: 4,
              },
              { text: '' },
              { text: '' },
              { text: '' },
              {
                text: '2.2 Identification No',
                style: 'fieldName',
                alignment: 'left',
                border: [false, true, true, false],
                colSpan: 4,
              },
              { text: '' },
              { text: '' },
              { text: '' },
              {
                text: '2.3 Age:',
                style: 'fieldName',
                alignment: 'left',
                border: [false, true, false, false],
              },
            ],
            [
              { text: '' },
              {
                style: 'data',
                text: 'MISS MALAI UDOMSUPRASERT',
                alignment: 'left',
                border: [true, false, false, true],
                colSpan: 4,
                margin: [20, 0, 0, 3],
              },
              { text: '' },
              { text: '' },
              { text: '' },
              {
                style: 'data',
                text: '3-1012-03047-48-1',
                alignment: 'center',
                border: [true, false, true, true],
                colSpan: 4,
                margin: [10, 0, 0, 0],
              },
              { text: '' },
              { text: '' },
              { text: '' },
              {
                border: [false, false, false, true],
                columns: [
                  {
                    style: 'data',
                    width: '*',
                    fontSize: 13,
                    text: '33',
                    alignment: 'left',
                    margin: [5, 0, 0, 2],
                  },
                  {
                    style: 'fieldName',
                    width: '*',
                    text: 'years',
                    alignment: 'right',
                    margin: [0, 0, 0, 2],
                  },
                ],
              },
            ],
            [
              { text: '' },
              {
                colSpan: 2,
                border: [true, true, true, true],
                columns: [
                  {
                    width: '*',
                    style: 'fieldName',
                    text: '2.4 Nationality',
                    alignment: 'left',
                    margin: [0, 1, 0, 2],
                  },
                  {
                    width: '*',
                    fontSize: 13,
                    style: 'data',
                    text: 'THAI',
                    alignment: 'left',
                    margin: [0, 1, 0, 2],
                  },
                ],
              },
              { text: '' },
              {
                colSpan: 4,
                border: [false, true, false, true],
                columns: [
                  {
                    width: '*',
                    style: 'fieldName',
                    text: '2.5 Province of Birth',
                    alignment: 'left',
                    margin: [0, 1, 0, 2],
                  },
                  {
                    width: '*',
                    fontSize: 13,
                    style: 'data',
                    text: 'Bangkok',
                    alignment: 'left',
                    margin: [0, 1, 0, 2],
                  },
                ],
              },
              { text: '' },
              { text: '' },
              { text: '' },
              {
                colSpan: 3,
                border: [false, true, false, true],
                columns: [
                  {
                    width: '*',
                    style: 'fieldName',
                    text: 'Country',
                    alignment: 'left',
                    margin: [0, 1, 0, 2],
                  },
                  {
                    width: '*',
                    fontSize: 13,
                    style: 'data',
                    text: 'KINGDOM OF THAILAND',
                    alignment: 'left',
                    margin: [-30, 1, 0, 2],
                  },
                ],
              },
              { text: '' },
              { text: '' },
            ],
            [
              { text: '' },
              {
                border: [true, false, false, false],
                columns: [
                  {
                    width: 70,
                    style: 'fieldName',
                    text: '2.6 Address:',
                    margin: [0, 3, 0, 0],
                  },
                  {
                    width: 400,
                    fontSize: 13,
                    style: 'data',
                    text: '90/51 Village No.11 Lat Sawai Sub-district, Lam Luk Ka District, Pathum Thani Province',
                    margin: [0, 1, 0, 0],
                  },
                ],
              },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '', border: [false, false, false, false] },
            ],
            [
              { text: '' },
              {
                style: 'data',
                text: '\n',
                alignment: 'left',
                border: [true, false, false, false],
                colSpan: 9,
                margin: [70, -4, 0, 5],
              },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
            ],
            [
              {
                text: '\n3.\nFather\n',
                bold: true,
                alignment: 'center',
                border: [false, false, false, true],
                fontSize: 16,
                rowSpan: 5,
                margin: [-5, 0, 0, 0],
              },
              {
                text: '3.1 Name - Surname',
                style: 'fieldName',
                alignment: 'left',
                border: [true, true, true, false],
                colSpan: 4,
              },
              { text: '' },
              { text: '' },
              { text: '' },
              {
                text: '3.2 Identification No',
                style: 'fieldName',
                alignment: 'left',
                border: [false, true, true, false],
                colSpan: 4,
              },
              { text: '' },
              { text: '' },
              { text: '' },
              {
                text: '3.3 Age: ',
                style: 'fieldName',
                alignment: 'left',
                border: [false, true, false, false],
              },
            ],
            [
              { text: '' },
              {
                style: 'data',
                text: 'MR. CHAIWASAN WATCHARASILACHAN',
                alignment: 'left',
                border: [true, false, false, true],
                colSpan: 4,
                margin: [20, 0, 0, 3],
              },
              { text: '' },
              { text: '' },
              { text: '' },
              {
                style: 'data',
                text: '3-5599-00167-85-6',
                alignment: 'center',
                border: [true, false, true, true],
                colSpan: 4,
                margin: [10, 0, 0, 0],
              },
              { text: '' },
              { text: '' },
              { text: '' },
              {
                border: [false, false, false, true],
                columns: [
                  {
                    style: 'data',
                    width: '*',
                    fontSize: 13,
                    text: '28',
                    alignment: 'left',
                    margin: [5, 0, 0, 2],
                  },
                  {
                    style: 'fieldName',
                    width: '*',
                    text: 'years',
                    alignment: 'right',
                    margin: [0, 0, 0, 2],
                  },
                ],
              },
            ],
            [
              { text: '' },
              {
                colSpan: 2,
                border: [true, true, true, true],
                columns: [
                  {
                    width: '*',
                    style: 'fieldName',
                    text: '3.4 Nationality',
                    alignment: 'left',
                    margin: [0, 1, 0, 2],
                  },
                  {
                    width: '*',
                    fontSize: 13,
                    style: 'data',
                    text: 'THAI',
                    alignment: 'left',
                    margin: [0, 1, 0, 2],
                  },
                ],
              },
              { text: '' },
              {
                colSpan: 4,
                border: [false, true, false, true],
                columns: [
                  {
                    width: '*',
                    style: 'fieldName',
                    text: '3.5 Province of Birth ',
                    alignment: 'left',
                    margin: [0, 1, 0, 2],
                  },
                  {
                    width: '*',
                    fontSize: 13,
                    style: 'data',
                    text: 'Nan',
                    alignment: 'left',
                    margin: [0, 1, 0, 2],
                  },
                ],
              },
              { text: '' },
              { text: '' },
              { text: '' },
              {
                colSpan: 3,
                border: [false, true, false, true],
                columns: [
                  {
                    width: '*',
                    style: 'fieldName',
                    text: 'Country',
                    alignment: 'left',
                    margin: [0, 1, 0, 2],
                  },
                  {
                    width: '*',
                    fontSize: 13,
                    style: 'data',
                    text: 'KINGDOM OF THAILAND',
                    alignment: 'left',
                    margin: [-30, 1, 0, 2],
                  },
                ],
              },
              { text: '' },
              { text: '' },
            ],
            [
              { text: '' },
              {
                border: [true, false, false, false],
                columns: [
                  {
                    width: 70,
                    style: 'fieldName',
                    text: '3.6 Address',
                    margin: [0, 3, 0, 0],
                  },
                  {
                    width: 400,
                    fontSize: 13,
                    style: 'data',
                    text: '90/51 Lat Sawai Sub-district, Lam Luk Ka District, Pathum Thani Province',
                    margin: [0, 1, 0, 0],
                  },
                ],
              },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '', border: [false, false, false, false] },
            ],
            [
              { text: '' },
              {
                style: 'data',
                text: ' \n',
                alignment: 'left',
                border: [true, false, false, false],
                colSpan: 9,
                margin: [70, -4, 0, 5],
              },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
            ],
            [
              {
                text: '4.\nBirth\nNotifying\nPerson',
                bold: true,
                alignment: 'center',
                border: [false, false, false, false],
                fontSize: 16,
                rowSpan: 3,
                margin: [-5, 0, 0, 0],
              },
              {
                text: '4.1 Name - Surname',
                style: 'fieldName',
                alignment: 'left',
                border: [true, true, true, false],
                colSpan: 4,
              },
              { text: '' },
              { text: '' },
              { text: '' },
              {
                text: '4.2 Identification No',
                style: 'fieldName',
                alignment: 'left',
                border: [false, true, true, false],
                colSpan: 4,
              },
              { text: '' },
              { text: '' },
              { text: '' },
              {
                text: '4.3 Age:',
                style: 'fieldName',
                alignment: 'left',
                border: [false, true, false, false],
              },
            ],
            [
              { text: '' },
              {
                style: 'data',
                text: 'MISS MALAI UDOMSUPRASERT',
                alignment: 'left',
                border: [true, false, false, true],
                colSpan: 4,
                margin: [20, 0, 0, 3],
              },
              { text: '' },
              { text: '' },
              { text: '' },
              {
                style: 'data',
                text: '3-1012-03047-48-1',
                alignment: 'center',
                border: [true, false, true, true],
                colSpan: 4,
                margin: [10, 0, 0, 0],
              },
              { text: '' },
              { text: '' },
              { text: '' },
              {
                border: [false, false, false, true],
                columns: [
                  {
                    width: '*',
                    fontSize: 13,
                    style: 'data',
                    text: '33',
                    alignment: 'left',
                    margin: [5, 0, 0, 2],
                  },
                  {
                    width: '*',
                    style: 'fieldName',
                    text: 'years',
                    alignment: 'right',
                    margin: [0, 1, 0, 2],
                  },
                ],
              },
            ],
            [
              { text: '' },
              {
                border: [true, false, false, true],
                columns: [
                  {
                    width: 70,
                    style: 'fieldName',
                    text: '4.4 Address',
                    margin: [0, 3, 0, 0],
                  },
                  {
                    width: 400,
                    fontSize: 13,
                    style: 'data',
                    text: '90/51 Village No.11 Lat Sawai Sub-district, Lam Luk Ka District, Pathum Thani Province',
                    margin: [0, 2, 0, 0],
                  },
                ],
              },
              { text: '', border: [false, false, false, true], colSpan: 8 },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
              { text: '' },
            ],
          ],
        },
        layout: {
          defaultBorder: false,
        },
      },
      {
        fontSize: 13,
        table: {
          widths: ['8.05%', '25.95%', '31%', '35%'],
          body: [
            [
              {
                text: '',
                style: 'fieldName',
                alignment: 'center',
                border: [false, false, true, false],
                fontSize: 13,
                margin: [-5, 0, 0, 0],
              },
              {
                border: [false, false, true, false],
                style: 'fieldName',
                text: '4.5 Relationship to the Newborn',
                margin: [0, 3, 0, 0],
              },
              {
                border: [false, false, true, false],
                style: 'fieldName',
                text: '4.6 Birth Certifying Document ',
                margin: [0, 3, 0, 0],
              },
              {
                border: [true, false, false, false],
                style: 'fieldName',
                text: '4.7 Birth Acknowledging Document ',
                margin: [0, 3, 0, 0],
              },
            ],
            [
              {
                text: '',
                style: 'fieldName',
                alignment: 'center',
                border: [false, false, true, true],
                fontSize: 13,
                margin: [-5, 0, 0, 0],
              },
              {
                border: [false, false, true, true],
                style: 'fieldName',
                text: 'Mother',
                margin: [0, 3, 0, 0],
              },
              {
                border: [false, false, true, true],
                style: 'fieldName',
                text: '303 / 254 ',
                margin: [0, 3, 0, 0],
              },
              {
                border: [true, false, false, true],
                style: 'fieldName',
                text: ' 20587 / 2548 ',
                margin: [0, 3, 0, 0],
              },
            ],
          ]
        },
      },
      {
        columns: [
          {
            width: 100,
            style: 'fieldName',
            text: 'Additional Records:',
            margin: [0, 6, 0, 0],
            alignment: 'left',
          },
          {
            width: '*',
            style: 'data',
            fontSize: 13,
            margin: [-1, 6, 0, 0],
            text: '',
          },
        ],
      },
      {
        style: 'data',
        text: 'Certified particulars from the Civil Registration Database\nOn 10 September 2019 \n........................................................................\n( MISS ACHIRAYA KRAISEE )\nRegistrar',
        alignment: 'center',
      }
    ],
    styles: {
      header: {
        bold: true,
        fontSize: 20,
        alignment: 'center',
      },
      fieldName: {
        fontSize: 13,
        bold: false,
      },
      data: {
        fontSize: 13,
        bold: true,
      },
    },
  }
  return layoutReal
}

export default { pdfBirth }
